import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import localFont from 'next/font/local'
import Header from "./_component/Header";
import Footer from "./_component/Footer";

const inter = Inter({ subsets: ["latin"] });
const canela = localFont({
  src: [
    {
      path: '../../public/Canela_Collection/Canela Family/Canela-Medium-Trial.otf',
      weight: '400'
    },
    {
      path: '../../public/Canela_Collection/Canela Family/Canela-Regular-Trial.otf',
      weight: '300'
    },
    {
      path: '../../public/Canela_Collection/Canela Family/Canela-Light-Trial.otf',
      weight: '200'
    },
    {
      path: '../../public/Canela_Collection/Canela Family/Canela-Thin-Trial.otf',
      weight: '150'
    },
    {
      path: '../../public/Canela_Collection/Canela Family/Canela-ThinItalic-Trial.otf',
      weight: '150'
    }
  ],
  variable: '--font-canela'
})
const neue = localFont({
  src: [
    {
      path: '../../public/bebas_neue/BebasNeue-Regular.otf',
      weight: '300'
    }
  ],
  variable: '--font-neue'
})
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${neue.variable} ${canela.variable}`}>
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
